apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tense-cricket-python-stage
  namespace: rhtap-test-organization-jk
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/tense-cricket-python/overlays/stage
    repoURL: https://github.com/rhtap-test-organization-jk/tense-cricket-python-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-stage
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap-test-organization-jk
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

