apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tense-cricket-python
  janus-idp.io/tekton: tense-cricket-python
  backstage.io/kubernetes-id: tense-cricket-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tense-cricket-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
