apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tense-cricket-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tense-cricket-python 
  name: tense-cricket-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tense-cricket-python 
